### ISSUE TITLE
Generate weekly reports for Water Board Members

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#17]
The water boards often do not have access to computers, meaning that we should be thinking about the visualizations app as a tool for them to use to monitor the plants... Can we make them aware that they can have access to Gràficos? Also, note that anyone in the community could check on their water system using the visualizations app... this could be used by regular community members to increase operators' transparency  (however, it might put the operators on edge... unsure/need to talk to them.) I think the immediate action item is to show the water board members of one of the plants (most likely Moroceli) the Gràficos visualizations, and let them play around with it, then ask the visualizations survey questions.

**Comment by jonschristensen** [comment]
On Wednesday 5/25 I was able to share the browser-based viewer with the water board in Morocelí - specifically their water system manager Oscar Trujillo and their secretary Sarah. When I asked Oscar about sharing live data with the public, he said he would prefer if there were some way for the water board to review it first. He suggested generating weekly or monthly reports for the water board leaders and the public. I think we should keep exploring full transparency with other operators and water boards, though. I'll check back in with Sarah and Oscar shortly for a survey.

**Comment by ethan92429** [comment]
@jonschristensen @wngrimshaw can y'all link a spreadsheet/ example of the current reports you give to the waterboards that we can implement?

**Comment by ethan92429** [comment]
moved to here: https://github.com/AguaClara/AguaClara.github.io/issues/11
