### ISSUE TITLE
Collect coagulant slider position

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#19]
If we collect the coagulant slider position, we can start to learn the relationship between the slider position and the dose. Then we can start recommending slider positions instead of dosages, we can monitor clogging in the dosing system.

**Comment by jonschristensen** [comment]
I really like this idea, here's a [decent picture](https://picasaweb.google.com/100703814570796592714/PlantaAguaClaraSanMatias20152016#6205664418995728546) of the ruler on the balance. Note that the 0.00 position does not always correspond exactly to zero dose, so the slider-dose model shouldn't necessarily pass through the origin (but should be linear).

It will be really interesting to study this over a long term in several plants to quantify the impact of clogging, like Ethan mentioned. I hesitate to let the operator shortcut the dosing process without thinking consciously and deliberately about the dose they're applying, so once we do have good slider predictions (and dose predictions) I'd still recommend displaying both slider position and dose to the operator.

**Comment by ethan92429** [comment]
@jacuerp I think this would also be nice to add to the Datos_v1.4 version... It would simply be another field with acceptable range 0-100... @jonschristensen do all of the CDC levers have those 0-100 markings?

**Comment by jonschristensen** [comment]
Some of the early CDC levers may not have these markings, but I know that Morocelí and Jesús de Otoro do, and future plants will.

**Comment by jacuerp** [comment]
@jonschristensen Is "posición del control deslizante de CDC" a good label?

**Comment by jonschristensen** [comment]
@jacuerp Will we be having separate fields for coagulant and chlorine? Or are we just tracking coagulant?

I think the operators will best understand "posición del deslizador de coagulante en la regla de la balanza (valor de 0-100 indicado en la ventanita del deslizador)" Is that too long? Maybe we could shorten it and include a tool tip...

**Comment by jonschristensen** [comment]
I was randomly thinking about this tool today and realized a small complication you may need to account for - the number of dosing tubes in use (valves open) at the time the dose and slider position are recorded. The plants are designed to have a fixed number of dosing tubes in use at a time (typically 2-3), with an extra tube offline for maintenance. But occasionally the operators will use fewer than the design number or all of the tubes including the extra for various reasons, and this can change from day to day and from operator to operator within the same plant.

We could assume they are always using the design number of tubes, but to be more rigorous we should either prompt them to readjust to the design number or have them fill in how many tubes are in use. Having them enter the number in use would allow them more flexibility, but you might need to include a diagram in the prompt to illustrate the info you want from them.

**Comment by ethan92429** [comment]
@jonschristensen thanks for the input! We are prompting them to return to the intended number of dosing tubes with a hint before they enter the coagulant slider position. I'm going to close this issue now.
