### ISSUE TITLE
Put backwash data into the plantdata form

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#21]
We need to require the operators to submit backwash times more. We can do this by asking them for the backwash time directly in the plantData form.

**Comment by jacuerp** [comment]
@ethan92429 I also put this in with Datos_v1.4

If they select "Yes", an additional page will show requesting a date and time of completion.

as a sidenote: I really don't like the swipe navigation. I think it's super clunky and too sensitive at this resolution. I looked around in the settings - there's an option to turn off swipe navigation and instead use navigational arrows at the bottom of the screen. Maybe we could think about including those steps in the setup tutorial we build later on?

**Comment by ethan92429** [comment]
@jacuerp I think having the additional page when they hit yes is good... we've got to be clear on the wording and we have to make sure that the Spanish side is properly translated. You could have W+J translate by posting the sentence(s) here and pinging them. Also, I like the idea of the arrows instead of the swiping. I think it is easier to understand. My vote is to change to arrows and if we get any negative feedback on it we'll reconsider. Also I'll add this to a Datos_v1.4 milestone.

**Comment by jonschristensen** [comment]
@jacuerp @ethan92429 The extra page looks good to me too. For the Spanish, I just have a small change: "Cuando realizó el retrolavado?"

**Comment by ethan92429** [comment]
@jacuerp The 1.4 form is not working... I just ran it on my emulator, and when I try to enter only plantdata, it doesn't ask me for any plant data! It only asks for backwash times. Did you thoroughly test the form before? Perhaps I'm missing something? Please let me know what you get.

**Comment by ethan92429** [comment]
@jacuerp things to change for 1.4 before release: 

1. I need to be able to see the Fusion Table... where is it located?
2. The backwash functionality is broken in several ways. a) Please ask how long the backwash lasted and restrict the answer in minutes to 5-60 b) when asking whether they have backwashed since last time in the plantdata portion of the film, we need to reword it so we are asking "Do you need to report a backwash?"... do you think that is sufficient? It's currently worded as " Have you initiated a backwash since the last time you entered data?," which might be interpreted as last time you entered plantData.... not sure on that confusion. c) Why doesn't the form ask which filter for the plants with multiple filters? We need them to record which filter they backwashed (1 or 2) and also when recording the entrance box heights. Tamara and San Matias have one filter. Atima, Agualteca, Ojojona and Cuatro communidades don't have filters, and the rest of the plants don't have filters. 
3. Please remove the units selector for flow rate and only ask for units in L/s. Anything else is a total headache! 
4. Make sure the coag slider position is between 0 and 100

Once you fix that, I'm sure I'll have some more comments! Great work.

**Comment by ethan92429** [comment]
Hi @jacuerp 
Do you happen to have a timeline for this? Turns out we're working in Tamara this week and I'd like to get it online, but I'm not sure if I should use the latest form.

**Comment by jacuerp** [comment]
@ethan92429 I can have it ready for you by tomorrow morning!

**Comment by jacuerp** [comment]
@ethan92429 Datos v1.4 is ready to download and submit over ODK. Let me know if it's what you are looking for.

A few issues: 
-I included structure for the filter box height edit, but excluded logic for when to show the prompt because I'm still unclear on the functionality you're asking for. If none of the plants have more than one filter, why are we asking for a filter number? Is there a typo here?

> Tamara and San Matias have one filter. Atima, Agualteca, Ojojona and Cuatro communidades don't have filters, and the rest of the plants don't have filters.

**Comment by ethan92429** [comment]
Oh no! I'm sorry about that Jay! There is totally a typo. Should read "the rest of the plants have two filters." So the rest need a filter 1 and filter 2 option. Whoopsies!!

**Comment by jacuerp** [comment]
@ethan92429 I thought I was losing my mind hehe. I'll make that change now. 

I made an edit to the comment above, can you also check that issue out for me?

**Comment by ethan92429** [comment]
@jacuerp I will check on it, but technically such a question should be asked in the other repos issues! :P. Anyways, my POST graficos is working perfectly. Did you download the latest from the playstore?

**Comment by ethan92429** [comment]
The form now asks if you have backwashed since the last reporting even when just filling out the plantdata info. Therefore I am closing this issue.
