### ISSUE TITLE
Change timeCollected and timeBackwashed to DateTime objects

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#22]
We need to make sure that all times that the form collects include the date, however, we do not want the operators to have to select the date that they uploaded every time (even if we are defaulting to the current day, it's still to messy to show them the date picker.) I propose that when we are trying to collect the times, we have the operators choose the specific hour and minute, and then they have three radio buttons to select that the data was either taken 'today', 'yesterday' or 'other'. If they select 'other,' than we can show them the date chooser on a new screen. Otherwise, all they will have to see is the hour and minute chooser (which should be defaulted to the current time anyways.) @jacuerp how does that sound? And is it possible to implement with the xforms? BTW, there is a great forum to ask about the xforms on google groups here if you get stuck: https://groups.google.com/forum/#!forum/opendatakit and for developer questions (how to extend odk/change the source code): https://groups.google.com/forum/#!forum/opendatakit-developers

**Comment by jacuerp** [comment]
@ethan92429 That sounds good to me. It's definitely doable with xforms. There's enough functionality at this point that even if there isn't an easy and explicit way to do something, someone will have figured out a clever workaround

**Comment by ethan92429** [comment]
This was implemented in form 1.4
