### ISSUE TITLE
Application doesn't display data

### ISSUE THREAD

**Issue by iamchriskelley** [AguaClara/POST#24]
I've downloaded the Post Graficos app onto a Galaxy S5 Active, selected a plant (Atima), and hit the Sincronizar button. The app appeared to hang at this point unless the wifi was connected. With the wifi connected, the data synchronization appeared to complete but I could not get the app to display a graph or table of data. Perhaps I am misunderstanding an aspect of the program's operation?

**Comment by ethan92429** [comment]
Thanks for trying it out, @iamchriskelley ! The reason (I hope) you didn't see data is because Atima is not submitting the POST form. Please try either Otoro or Moroceli. You can essentially see the app itself in browser form here: http://aguaclara.github.io/

**Comment by iamchriskelley** [comment]
That was it. Thanks for the quick response! App is looking good.
