### ISSUE TITLE
Change form to make scrolling more obvious

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#26]
In the emulator, it's hard to scroll, and so I didn't even notice there was more to fill out in the plant data page. I didn't notice it, and I don't think the operators at Atima noticed it when they were trying out 1.4, hence this might be a serious UI problem. How can we indicate they need to scroll down if it's not intuitive? Perhaps we should just make all those plant data fields required when that plantdata page comes up, so if they try to progress forward without entering anything, an ODK error pops up (I think that is the ODK behavior!) Any other ideas?

**Comment by ethan92429** [comment]
@jacuerp

**Comment by jacuerp** [comment]
@ethan92429  That seems like the most elegant and cohesive solution! The only other option it seems would be to restructure the form so that no scrolling is necessary, which would mean defining the form fields in separate groups so that each question occurs on a different page.

**Comment by ethan92429** [comment]
Awesome! Glad you like that idea. I think if they hit the plantdata checkbox, they should need to fill everything out... The catch is that some plants don't have filters, and so we shouldn't be requesting filter box height in the plantdata form for those plants... I think it's high time that we don't hardcode plant info directly into the form. Especially considering we are soon going to have Las Vegas online. In the meantime, you can make all the plantdata forms required because all the filters we have using POST (except Atima) have filters.

**Comment by jacuerp** [comment]
@ethan92429 I updated the form version to include this functionality. All you have to do is instruct the operators to delete Datos v1.4 and re-download it. On the Get Blank Form screen, there should be a 'Version' field in the subtext of the form now in addition to the ID field which should read Version: 2016091401.

**Comment by ethan92429** [comment]
Confirmed this is done. @jacuerp please remove Datos v1.5 if you are not using it so we don't confuse the operators.
