### ISSUE TITLE
Distributing Datos_v1.4

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#29]
Hi @jacuerp. This issue is for tracking the deployment of datos v1.4. We've had a few problems here in Honduras. Jesus de Otoro has stopped sending data way back in August, Morocelí stopped back in September, and San Nicolas had a short time back in early august. Currently, no one is regularly sending data. Apparently Morocelí has a problem with their phone that I need to investigate, but unfortunately that plant is a ways away and I won't get there for quite a few weeks (probably a month). However, I have a bunch of fun suggestions! :)
1. in plant data, we should be asking for water level in filter box 1 and water level in filter box 2 if the plant has two filters! Currently Morocelí form just asks what the filter box height is which is misleading considering they have 2. 
2. Similar to number one, the filter box height question should disappear for the plants that don't have filters.... in conclusion, there are three ways that question should show up... for plants with no filters it shouldn't show, for plants with one, it should say what it does now, and for plants with two it needs to ask twice, each specifying filter one or filter two. 
3. Don't ask if they've performed a backwash if they don't have filters. 
4. I don't understand the "Which filter are you reporting for" question... is that supposed to be a solution to problem 2 with the entrance tank? What if they want to report entrance tank levels for both filters? I think this question should be taken out and you should solve it like number 2 suggests. 
5. When asking which filter you backwashed, it should allow you to select both for times in which you did! (checkboxes instead of radio buttons) and furthermore, the subsequent boxes should be asking about backwashing twice if they said they backwashed both. 
6. When asking what time the backwash finished, can you make that time selector vertical? It shows as scrolling horizontal for me, which is confusing on the small-screen phone I use. 
That's it for now. You must be getting frustrated by how many times you have to change this! Have you figured out a good flow that doesn't require switching to a new fusion table and migrating past data?

**Comment by jacuerp** [comment]
I have one solution for making small changes on the fly in logic or form organization, but unfortunately ODK just doesn't seem to have a solution if we're making structural changes to the data that is submitted. But the workaround is more or less simple, especially since there's really no point for me to actually go through with it until the new form version is 100% vetted and sent out into the world.

Thanks for all the detail, I think I've been unclear on exactly what it means for a plant to have 2, 1, or no filters, and what the reporting process is for each of these situations. I'll have this ready for you soon!

Do you know what's wrong in Moroceli? Or is it just vaguely broken

**Comment by jacuerp** [comment]
@ethan92429 All done with this, check it out when you can!

I also can't replicate #6 on my device. Can you give a little more detail? i.e. where in the form this question occurs relative to others, version of ODK Collect on your device, etc. Thanks!

**Comment by ethan92429** [comment]
Number 6 is not a big deal and may be device specific. I tested the rest of the form and I have a couple small things. First off, now the date and time for backwash are on separate screens... was that true before as well? Second, the backwash time prompt should also have a specified units... should ask for duration of BW in minutes. I'll add some more comments by Monday.

**Comment by ethan92429** [comment]
@jacuerp carefully review the Spanish hints. They are all in English... And the units of the answer should always go in () after the label of the prompt. This should have been caught during earlier testing. Also, I'm not seeing my form results in the Datos v1.4 table after I send the form. Were you able to have the aggregate server send the info to the Fusion Table? Also, I wish we could have one database rather than different tables for each version! But I suppose that's what we need until we've finalized our form logic.

**Comment by jacuerp** [comment]
@ethan92429  made the suggested changes to Datosv1.4.1. Check it out when you've got da time.

**Comment by ethan92429** [comment]
@jacuerp sounds good! Is it on the Github?

**Comment by ethan92429** [comment]
Version 1.4 is released on Moroceli. Now we're working on 1.5.
