### ISSUE TITLE
Storing ODK forms?

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#30]
Hi @jacuerp where are you storing the ODK forms? Dane made a repo (post.odkforms) that I think we should use to store them. I have a few small language things I want to change, so I'm going to pull the form, make the changes, and push to that repo. Does that work?

**Comment by ethan92429** [comment]
@jacuerp also, I think we should be storing the odkbuild file if that's what you are building it with, or the .xls if that is what you're using to build. Or are you working directly in the xml form?

**Comment by jacuerp** [comment]
@ethan92429 All good ideas. Right now the forms are stored both on ODK Aggregate, and locally. I'll start a habit of uploading to Git as well, each time a new form version goes up.

 I work directly with the .xml files because odkbuild doesn't have the fine-tuning capabilities we need.

**Comment by ethan92429** [comment]
@jacuerp Thanks!
