### ISSUE TITLE
Phone donors

### ISSUE THREAD

**Issue by jacuerp** [AguaClara/POST#32]
@ethan92429 We can use this issue to track the phone donation plan. 

Question: I assume our goal is expansion, but I 'm not sure what the horizon for POST looks like. How many phones are we trying to secure, at what price point?

**Comment by ethan92429** [comment]
@jacuerp Let's start with trying for one for each plant and one for testing... A total of 15 phones. If we can get a discount, that'd be good too. We can get basic smartphones for about $50, so it would be great to have that knocked down to $20. The horizon of POST is putting it in all the AguaClara plants and hopefully some plants outside the AC program.

**Comment by ethan92429** [comment]
Hi @jacuerp any updates on this? Only reason I ask is that we'll be needing a phone soon for Las Vegas.
