### ISSUE TITLE
Login for Wiki Setting up POST on ODK Collect

### ISSUE THREAD

**Issue by asm278** [AguaClara/POST#33]
In [Setting-up-POST-on-ODK-Collect](https://github.com/AguaClara/POST/wiki/Setting-up-POST-on-ODK-Collect) Step 3 indicates to log in to ODK Collect.

Can this step be removed? From testing it seems that the login step is superfluous, the data doesn't seem to be logged any differently for logged in users, and the forms seem available to anonymous (not logged in) users.

**Comment by ethan92429** [comment]
@asm278 You are right! I allowed anonymous users to submit data on the new servers. My bad. I just fixed both and you have to now input a UN and PW to be able to login. We can definitely discuss security later, but for now we're just manually handing out the UN and PW... This way at least it makes it tougher for bots and other internet malcontents to post erroneous data. Do you think that's sufficient for now?
